# Generated by Django 5.0 on 2023-12-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedvideo',
            name='subtitles',
            field=models.TextField(blank=True),
        ),
    ]
