# Generated by Django 5.0 on 2024-01-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_uploadedvideo_subtitles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedvideo',
            name='subtitles',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
