# Generated by Django 5.0 on 2024-01-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_remove_uploadedvideo_subtitles_subs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subs',
            name='subtitles',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
