# Generated by Django 5.0 on 2024-01-02 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_alter_subs_subtitles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subs',
            name='subtitles',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
