# Generated by Django 5.0 on 2024-01-03 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Subs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitles', models.FileField(blank=True, upload_to='subs/')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploadVideo.uploadedvideo')),
            ],
        ),
    ]
